### ISSUE TITLE
Would it be better to separate IdentityServer in different project?

### ISSUE THREAD

**Issue by karlbal** [jasontaylordev/NorthwindTraders#206]
This is just out of curiosity. Because I observed some people do this.

**Comment by Pyrobolser** [comment]
I am also interested in this answer. It seems like Jason is suggesting this [in this video](https://youtu.be/Zygw4UAxCdg?t=1925).  
I am also interested into, why or why not, I suppose it is a matter of complexity but how would you pick one rather than the other, what would be your criteria?  
If anybody would like to debate on the subject.

Thanks.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
