### ISSUE TITLE
[Discussion] Should DbSet<T> be abstracted away just like DbContext

### ISSUE THREAD

**Issue by hcvo** [jasontaylordev/NorthwindTraders#216]
Hi Jason,

Will you consider abstracting away the `DbSet<T>` in INorthwindDbContext so that INorthwindDbContext will be completely independent from EF? And thus we can swap out SqlServer provider to use any data provider that is not supported by EF such as NoSql Db providers?

Exemple code belows:

```
    public interface INorthwindDbSet<T>
    {
         void AddRange(IEnumerable<T> entities);
         ….
    }
    public class NorthwindDbSet<T> : DbSet<T>, INorthwindDbSet<T>, IEnumerable<T>, IQueryable<T> 
    {
        .....
    }


    public interface INorthwindDbContext
    {
        IDbSet<Category> Categories { get; set; }

        IDbSet<Customer> Customers { get; set; }

        IDbSet<Employee> Employees { get; set; }

        IDbSet<EmployeeTerritory> EmployeeTerritories { get; set; }

        IDbSet<OrderDetail> OrderDetails { get; set; }

        IDbSet<Order> Orders { get; set; }

        IDbSet<Product> Products { get; set; }

        IDbSet<Region> Region { get; set; }

        IDbSet<Shipper> Shippers { get; set; }

        IDbSet<Supplier> Suppliers { get; set; }

        IDbSet<Territory> Territories { get; set; }

        Task<int> SaveChangesAsync(CancellationToken cancellationToken);
    }

```

**Comment by Hellevar** [comment]
DbSet is an implementation of the repository pattern, you don't need to put it in another repository abstraction. The same for DbContext - it is an implementation of UnitOfWork.

**Comment by CrispyDrone** [comment]
The point is to abstract away a dependency on entity framework, not to add an unnecessary wrapper around DbSet and UnitOfWork for the heck of it.

Right now your entire application's logic is still dependent on an external library, which degrades the infrastructure layer, as that is the main (or entire) reason the infrastructure layer exists in the first place.

I don't think it's a pragmatic issue since it seems highly unlikely you would ever make a switch from sql to no sql or even switch away from using Entity Framework to something else, but from a purist viewpoint, it would be nice to be able to say *all* external dependencies are part of the infrastructure layer.

**Comment by jasontaylordev** [comment]
Thank you for your interest in this project. This repository has been archived and is no longer actively maintained or supported. We appreciate your understanding. Feel free to explore the codebase and adapt it to your own needs if it serves as a useful reference. If you have any further questions or concerns, please refer to the README for more information.
